export const ACTION_ADD_SLIDE_PAGE = "ACTION_ADD_SLIDE_PAGE";
export const ACTION_ADD_SLIDE_PAGE_SUC = "ACTION_ADD_SLIDE_PAGE_SUC";

export const ACTION_FETCH_PAGE_TEMPLATES = "ACTION_FETCH_PAGE_TEMPLATES";
export const ACTION_FETCH_PAGE_TEMPLATES_SUC =
  "ACTION_FETCH_PAGE_TEMPLATES_SUC";
